### ISSUE TITLE
[FEATURE REQUEST] CLI support for image-classification

### ISSUE THREAD

**Issue by billytcl** [huggingface/autotrain-advanced#608]
### Feature Request

I'm trying to use the CLI for image classification on autotrain-advanced local but I'm running into the error:

```
Exception: Image classification is not yet supported for local datasets using the CLI. Please use UI.
```

What is the roadmap for this feature to be enabled?

### Motivation

We have large numbers of batches that we'd like to automate the autotrain process (running locally) and try different model architectures. Using a UI would be really cumbersome.

**Comment by abhishekkrthakur** [comment]
it just means that local dataset support is not there. you can still upload your dataset to huggingface hub and use it for training using the cli. is that possible for you?

**Comment by billytcl** [comment]
I have 290 different datasets to go through so doing it through the UI
would be a pain!

**Comment by abhishekkrthakur** [comment]
i didnt ask you to use UI.
Lemme rephrase: are your image datasets on huggingface hub? if yes, you can use them directly in the CLI

**Comment by billytcl** [comment]
Oh I got it! Let me give that a shot.

Billy

**Comment by abhishekkrthakur** [comment]
CLI now supports image classification. 
Example config:

```
task: image_classification
base_model: google/vit-base-patch16-224
project_name: autotrain-local-flowers-finetuned
log: tensorboard
backend: local

data:
  # path contains the training and validation folders
  path: Datasets/image_classification/flowers
  train_split: train # this is the training folder, containing subfolders with classnames and images inside the subfolders
  valid_split: null # if you have a validation folder, use its name here
  column_mapping: # dont touch for local datasets
    image_column: image
    target_column: labels

params:
  epochs: 2
  batch_size: 4
  lr: 2e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true

```
