### ISSUE TITLE
Is it possible to tweak the adamw_torch optimizer to change Beta1 and Beta2 values?

### ISSUE THREAD

**Issue by jackswl** [huggingface/autotrain-advanced#743]
As per title,

```
  optimizer: adamw_torch
```
How can I tweak the beta1 and beta2 values in my .yml file?

@abhishekkrthakur  wondering if this is possible. thanks!

**Comment by abhishekkrthakur** [comment]
which task?

**Comment by jackswl** [comment]
sorry, forgot to specify in details. It is for LLM fine-tuning

```
task: llm-sft
base_model: xxx
project_name: xxx
log: none
backend: local

data:
  path: xxx
  train_split: train
  valid_split: null
  chat_template: null
  column_mapping:
    text_column: text

params:
  block_size: 1024
  model_max_length: 1024
  epochs: 3
  batch_size: 4
  lr: 1e-4
  peft: true
  quantization: int4
  target_modules: "q_proj,v_proj,o_proj,k_proj"
  padding: right
  optimizer: adamw_torch
  scheduler: cosine
  gradient_accumulation: 4
  mixed_precision: bf16     
  warmup_ratio: 0.1
  weight_decay: 0.1
  lora_r: 16
  lora_alpha: 16
  lora_dropout: 0
  merge_adapter: false
  use_flash_attention_2: true  
  logging_steps: 1
  unsloth: false

hub:
  username: xx
  token: hf_XXX
  push_to_hub: false
```

Is there a way to tweak the beta1 and beta2 values for adamw_torch to 0.9 and 0.95 respectively for beta1 and beta2?
