### ISSUE TITLE
Do we need to insert bos and eos tokens fully in the train.csv?

### ISSUE THREAD

**Issue by jackswl** [huggingface/autotrain-advanced#753]
When fine-tuning LLM using train.csv, does the sample require the full template which includes the **bos and eos?**

For example, if the model bos_token is ```<s>```, do I need to include it into the train.csv sample as well?

**Comment by jackswl** [comment]
@abhishekkrthakur, for example, for mistral 7b instruct v0.3,
will each of the example in train.csv look something like this in the text column:
```<s>[INST] hi this is user[/INST] this is assistant </s>```

is this right? it will include the entire

**Comment by abhishekkrthakur** [comment]
you dont need to format dataset and keep it in json format if using chat template. for example no_robots dataset. if you dataset is plain test and you are training a chat model, you need to add special tokens and tags. there is a parameter that can add end token by the way.

**Comment by jackswl** [comment]
@abhishekkrthakur, i am currently using plain text. However, my plain text already contains all the special tokens and tags from pre-applying the chat template myself. Is this approach ok?

so for example, one of my sample inside train.csv can be:
```<s>[INST] hi this is user[/INST] this is assistant </s>```, which is already applied with the chat template beforehand. Just double confirming that this is ok for autotrain? So my train.csv will contains all the plain text in text column that already applied with chat template.

**Comment by abhishekkrthakur** [comment]
yes. in that case, make sure `chat_template` is set to none.

**Comment by jackswl** [comment]
ok thanks for the swift reply. was trying to re-confirm, so I don't get errors like having **EOS token applying again** on top of my train.csv during fine-tuning.

**Comment by jackswl** [comment]
@abhishekkrthakur for example:

messages = '''<s>[INST] You are an expert Python programmer. Your task is to do this.[/INST]
assistant goes here
</s>'''

tokenizer(messages) <-- this will output <s> again

By doing this, the <s> will be applied again. So I was wondering if autotrain will do this for my plain text? or should my plain text include all special tags EXCEPT **BOS token**?

**Comment by abhishekkrthakur** [comment]
choose llm generic and disable option to add end token and it will be fine.

**Comment by jackswl** [comment]
@abhishekkrthakur Could you help on this? Just re-clarifying. This is my original .yml file below. Do I change the task from ```llm-sft``` to ```llm```, then insert ```add_eos_token: false``` under ```data```, then also add ```trainer: default``` under ```data```? Did I leave out anything?

```
task: llm-sft
base_model: /scratch/xxx
project_name: xxx
log: none
backend: local

data:
  path: /home/xxx
  train_split: train
  valid_split: null
  chat_template: null
  column_mapping:
    text_column: text

params:
  block_size: 4096
  model_max_length: 4096
  epochs: 4
  batch_size: 4 
  lr: 1e-4 
  peft: true
  quantization: int4
  target_modules: all-linear
  padding: right
  optimizer: adamw_torch
  scheduler: cosine
  merge_adapter: false
  use_flash_attention_2: true   
  logging_steps: 1
  unsloth: false
  seed: 42
```
