### ISSUE TITLE
[BUG] autotrain process returns code 0 even if there was an error in worker during train process

### ISSUE THREAD

**Issue by mmx86** [huggingface/autotrain-advanced#877]
### Prerequisites

- [x] I have read the [documentation](https://hf.co/docs/autotrain).
- [x] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

`autotrain --config config.yaml && echo "must be executed only on success"`

with test config:
```
backend: local
base_model: svmm  # just testing invalid case. It doesn't matter where the invalidation is
data:
  column_mapping: {}
  path: autotrain
  train_split: train
  valid_split: test
log: tensorboard
project_name: project
target_columns: target
task: tabular
```

### Error Logs

ERROR    | 2025-03-28 07:03:14 | autotrain.trainers.common:wrapper:216 - Invalid model
INFO     | 2025-03-28 07:03:16 | autotrain.parser:run:229 - Job ID: 2580
must be executed only on success

### Additional Information

I expected job error codes to be forwarded to parent autotrain process to be able to integrate autotrain into some pipeline depending on the success of the execution.
