### ISSUE TITLE
[FEATURE REQUEST] problem_type = "multi_label_classification"

### ISSUE THREAD

**Issue by vinnitu** [huggingface/autotrain-advanced#905]
### Feature Request

I saw only tabular_multi_label_classification, how about task text_classification with multi_label_classification problem_type?

I have data format like this

```jsonl
{ "text": "...", "labels": ["label1", "label2"]}
{ "text": "...", "labels": ["label3"]}
```

here is my config.yaml

```yaml
task: text_classification
base_model: FacebookAI/xlm-roberta-base
project_name: tickets
log: tensorboard
backend: local

data:
  path: .
  train_split: train
  valid_split: null
  column_mapping:
    text_column: text
    target_column: tags
  test_size: 0
  seed: 42

params:
  problem_type: multi_label_classification
  max_seq_length: 512
  epochs: 1
  batch_size: 4
  lr: 2e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16
``` 

### Motivation

It is typical task for me - to get ticket problem (labels)
